### ISSUE TITLE
Unix IO

### ISSUE THREAD

**Issue by tpfau** [sysbiolux/FALCON#10]
At the moment the code depends on the xlswrite functionality to write the model files (also in csv format). This causes issues when running the code on a linux/unix machine, as xlswrite depends on a working excel installation.
I would suggest to convert the csv output generation to readtable (i.e. convert the cell array to a table and write the table instead of the cellarray). This should work with anything from 2013b onwards.

**Comment by sdelandtsheer** [comment]
Done for all scripts which write results in xls tables.
More scripts depend on xlswrite function. Notably network extension in the case of many-input Boolean gates. These need to be changed as well. Then the functionality of FALCON under unix has to be assessed again.

**Comment by philippelucarelli** [comment]
should be fixed now
